name: Parse-dpkg
on: push
jobs:
  Parse-dpkg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Change directory
        run: cd debian

      - name: Create Packages file
        run: dpkg-scanpackages --multiversion . > Packages

      - name: gzip Packages file
        run: gzip -k -f Packages

      - name: Create Release file
        run: apt-ftparchive release . > Release

      - name: Import private GPG key
        run: echo -n "$APT_SIGNING_KEY" | gpg --import
        env:
          APT_SIGNING_KEY: ${{secrets.APT_SIGNING_KEY}}

      - name: Sign Release file
        run: gpg --default-key linux@armcord.app -abs -o - Release > Release.gpg

      - name: Sign InRelease file
        run: gpg --default-key linux@armcord.app --clearsign -o - Release > InRelease

      - name: Commit files
        run: |
          git config user.name "APT Repository Maintainer"
          git config user.email "action@github.com"
          git add . || true
          git commit -m "Add APT information for release"
          git push -f || true
