name: Parse-dpkg
on: push
jobs:
  Parse-dpkg:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout files
        uses: actions/checkout@v4

      - name: Create Packages file
        run: dpkg-scanpackages --multiversion . > Packages

      - name: gzip Packages file
        run: gzip -k -f Packages

      - name: Create Release file
        run: apt-ftparchive release . > Release

      - name: Write private GPG key to file
        run: echo -n "$APT_SIGNING_KEY" > private.key
        env:
          APT_SIGNING_KEY: ${{secrets.APT_SIGNING_KEY}}

      - name: Import private GPG key
        run: gpg --yes --pinentry-mode loopback --passphrase "$GPG_PASSWORD" --import private.key
        env:
          GPG_PASSWORD: ${{secrets.GPG_PASSWORD}}

      - name: Sign Release file
        run: gpg --pinentry-mode loopback --passphrase "$GPG_PASSWORD" --default-key linux@armcord.app -abs -o - Release > Release.gpg
        env:
          GPG_PASSWORD: ${{secrets.GPG_PASSWORD}}

      - name: Sign InRelease file
        run: gpg --pinentry-mode loopback --passphrase "$GPG_PASSWORD" --default-key linux@armcord.app --clearsign -o - Release > InRelease
        env:
          GPG_PASSWORD: ${{secrets.GPG_PASSWORD}}

      - name: Commit files
        run: |
          git config user.name "APT Repository Maintainer"
          git config user.email "action@github.com"
          git add . || true
          git add !*.key || true
          git commit -m "Add APT information for release"
          git push -f || true
